--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: delivery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    delivery_address character varying(255) NOT NULL,
    delivery_status character varying(255),
    delivery_time time(6) without time zone,
    delivery_mode character varying(255),
    pickup_time time(6) without time zone,
    delivery_person_id bigint,
    order_id bigint,
    CONSTRAINT delivery_delivery_mode_check CHECK (((delivery_mode)::text = ANY ((ARRAY['PICKUP'::character varying, 'DELIVERY'::character varying])::text[]))),
    CONSTRAINT delivery_delivery_status_check CHECK (((delivery_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'READY_FOR_PICKUP'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.delivery OWNER TO postgres;

--
-- Name: delivery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delivery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_items (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255),
    price numeric(38,2),
    type character varying(255),
    restaurant_id bigint,
    CONSTRAINT menu_items_type_check CHECK (((type)::text = ANY ((ARRAY['VEGETARIAN'::character varying, 'NONVEGETARIAN'::character varying, 'VEGAN'::character varying])::text[])))
);


ALTER TABLE public.menu_items OWNER TO postgres;

--
-- Name: menu_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price numeric(38,2),
    quantity integer,
    menu_item_id bigint,
    order_id bigint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    price numeric(38,2),
    type smallint,
    user_id bigint,
    CONSTRAINT orders_type_check CHECK (((type >= 0) AND (type <= 1)))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_type character varying(255),
    status character varying(255),
    transaction_id character varying(255),
    order_id bigint,
    CONSTRAINT payments_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'NET_BANKING'::character varying, 'UPI'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'COMPLETED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255) NOT NULL,
    closing_time time(6) without time zone,
    email character varying(255),
    latitude double precision,
    location character varying(255),
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    opening_time time(6) without time zone,
    phone_number character varying(255),
    rating numeric(38,2),
    owner_id bigint
);


ALTER TABLE public.restaurants OWNER TO postgres;

--
-- Name: restaurants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    role character varying(255),
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'DELIVERY'::character varying, 'OWNER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: delivery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.delivery (id, created_at, updated_at, delivery_address, delivery_status, delivery_time, delivery_mode, pickup_time, delivery_person_id, order_id) FROM stdin;
22	2025-07-16 11:33:29.849788	2025-07-16 12:06:43.43819	321 Maple Avenue, Riverdale, Country	CONFIRMED	14:30:00	DELIVERY	12:06:43.429	2	22
21	2025-07-16 10:25:04.70724	2025-07-16 12:11:58.951832	2031 South Clark Street, APT. 1906	READY_FOR_PICKUP	15:30:00	PICKUP	12:11:58.95	1	21
\.


--
-- Data for Name: menu_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.menu_items (id, description, name, price, type, restaurant_id) FROM stdin;
6	Classic Italian pizza with tomatoes, mozzarella, and basil	Margherita Pizza	12.99	VEGETARIAN	3
7	Spicy grilled paneer cubes with onions and bell peppers.	Paneer Tikka	10.49	VEGETARIAN	3
11	Aromatic basmati rice cooked with tender chicken and spices.	Chicken Biryani	13.99	NONVEGETARIAN	4
12	Spicy grilled paneer cubes with onions and bell peppers.	Paneer Tikka	10.49	VEGETARIAN	4
13	Fresh romaine lettuce with croutons and parmesan	Caesar Salad	8.99	VEGETARIAN	5
14	Sizzling chicken with peppers and onions	Chicken Fajitas	13.99	NONVEGETARIAN	5
15	Fresh avocado with lime and cilantro	Guacamole	5.99	VEGETARIAN	6
16	Mixed greens with steak strips	Steak Salad	18.99	NONVEGETARIAN	7
17	Creamy mashed potatoes	Mashed Potatoes	4.99	VEGETARIAN	8
18	20oz prime ribeye	Ribeye Steak	29.99	VEGAN	7
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, price, quantity, menu_item_id, order_id, created_at, updated_at) FROM stdin;
41	12.99	1	6	21	2025-07-16 10:25:04.711221	2025-07-16 10:25:04.711235
42	10.49	3	7	21	2025-07-16 10:25:04.71367	2025-07-16 10:25:04.71368
43	13.99	1	11	22	2025-07-16 11:33:29.854633	2025-07-16 11:33:29.854644
44	10.49	2	12	22	2025-07-16 11:33:29.856319	2025-07-16 11:33:29.856328
45	18.99	2	16	23	2025-07-16 11:39:22.238059	2025-07-16 11:39:22.238091
46	5.99	1	15	23	2025-07-16 11:39:22.240398	2025-07-16 11:39:22.240408
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, created_at, updated_at, price, type, user_id) FROM stdin;
21	2025-07-16 10:25:04.69555	2025-07-16 10:25:04.695584	44.46	1	2
22	2025-07-16 11:33:29.838569	2025-07-16 11:33:29.8386	34.97	1	2
23	2025-07-16 11:39:22.228412	2025-07-16 11:39:22.228424	43.97	0	1
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (id, paid_at, payment_type, status, transaction_id, order_id) FROM stdin;
21	2025-07-16 10:25:04.714548	CREDIT_CARD	SUCCESS	955e05d8-480b-433b-be90-78daa15d8126	21
22	2025-07-16 11:33:29.857273	DEBIT_CARD	SUCCESS	fa38731f-d9ff-422d-a1a4-ebec015386ae	22
23	2025-07-16 11:39:22.242518	UPI	SUCCESS	9336dfea-787c-46f0-a1fc-0d31560aeb1b	23
\.


--
-- Data for Name: restaurants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants (id, created_at, updated_at, address, closing_time, email, latitude, location, longitude, name, opening_time, phone_number, rating, owner_id) FROM stdin;
3	2025-07-15 05:13:47.465572	2025-07-15 05:13:47.465606	123 Main St, New York, NY 10001	23:00:00	info@pizzapalace.com	40.7589	Times Square	-73.9851	Pizza Palace	11:00:00	1234567890	4.00	4
4	2025-07-15 05:15:50.229703	2025-07-15 05:15:50.22977	789 Sushi St, San Francisco, CA 94101	22:00:00	info@sushimaster.com	37.8044	Fisherman's Wharf	-122.4099	Sushi Master	12:00:00	5551234567	4.00	4
5	2025-07-15 05:16:30.33455	2025-07-15 05:16:30.334594	123 Italian Ave, Los Angeles, CA 90001	23:00:00	info@labellapasta.com	34.0522	Downtown LA	-118.2437	La Bella Pasta	11:30:00	5559876543	4.00	4
6	2025-07-15 05:17:12.619587	2025-07-15 05:17:12.619639	456 Steak St, Chicago, IL 60601	00:00:00	info@primecutsteakhouse.com	41.8781	The Loop	-87.6298	Prime Cut Steakhouse	17:00:00	5554567890	4.00	6
7	2025-07-15 05:17:54.547413	2025-07-15 05:17:54.547472	321 Mexican St, Houston, TX 77001	22:30:00	info@tacofiesta.com	29.7604	Downtown Houston	-95.3698	Taco Fiesta	11:00:00	5557890123	4.00	6
8	2025-07-15 05:18:07.111685	2025-07-15 05:18:07.111733	789 Vegan Ave, Austin, TX 73301	21:00:00	info@greenplate.com	30.2672	Downtown Austin	-97.7431	Green Plate	10:00:00	5553456789	4.00	6
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, updated_at, address, email, password, phone_number, role, username) FROM stdin;
1	2025-07-15 04:30:13.810019	2025-07-17 19:43:35.484647	123 Main St, New York, NY 10001	john.doe@example.com	$2a$10$PBews129pcRTX8ltQXIRa.dtwQHBY0RMK3RxdMsH6t2gVo2sir9CO	+1234567890	USER	john_doe
2	2025-07-15 04:30:57.719082	2025-07-17 19:43:35.599707	456 Admin Ave, Washington, DC 20001	admin@example.com	$2a$10$ZvQzYl.4TpPyjNNFv3Xko.JFcgxfdSXCotut4ECAfWZLoyvtmpY9O	+1987654321	ADMIN	admin_user
3	2025-07-15 04:35:33.227113	2025-07-17 19:43:35.696785	789 Delivery Rd, Chicago, IL 60601	delivery.person@example.com	$2a$10$NMvnWOJNhgigvEbIvClK9./MuB3LWaIb6xpMKerrjEhihxHOw.gZG	+1555123456	DELIVERY	delivery_guy
4	2025-07-15 04:37:38.466879	2025-07-17 19:43:35.797429	321 Restaurant St, Los Angeles, CA 90001	owner@example.com	$2a$10$fBO0iWUZhu5cIFJIYUAOr.KfkwqQdKBurn8EeoiJBDuuQ1XjZInfq	+1888123456	OWNER	restaurant_owner
5	2025-07-15 04:39:21.829692	2025-07-17 19:43:35.898643	456 Oak Ave, Los Angeles, CA 90001	jim.osei@example.com	$2a$10$DUNp5ft06z/D9Y8J6QhsWO.9dyJGpgkKjEBbalPK6OxJI1CBhEfIO	+1666123456	ADMIN	jim_osei
6	2025-07-15 05:14:38.190729	2025-07-17 19:43:36.001295	456 Market St, Austin, TX 73301	jane.owner@example.com	$2a$10$4ZnVUf5FG2MyErsnGzwNQeI1AUe4sGeh3k9xV14JFMap2JDBTah0m	+14445556666	OWNER	owner_jane
\.


--
-- Name: delivery_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.delivery_id_seq', 23, true);


--
-- Name: menu_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_items_id_seq', 18, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 46, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 23, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 23, true);


--
-- Name: restaurants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_id_seq', 8, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: delivery delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_pkey PRIMARY KEY (id);


--
-- Name: menu_items menu_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT menu_items_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: restaurants restaurants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);


--
-- Name: delivery uk3bdrbd2jcybaaa5rxkj4s7vlk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT uk3bdrbd2jcybaaa5rxkj4s7vlk UNIQUE (order_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- Name: restaurants ukfe6aq2gbudopv20yl6b77798m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT ukfe6aq2gbudopv20yl6b77798m UNIQUE (email);


--
-- Name: payments uklryndveuwa4k5qthti0pkmtlx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uklryndveuwa4k5qthti0pkmtlx UNIQUE (transaction_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: restaurants ukthig4i0d3mocamrqyupicmm61; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT ukthig4i0d3mocamrqyupicmm61 UNIQUE (phone_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fkdtfg1f49yr5yye2fpl2xid2xo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkdtfg1f49yr5yye2fpl2xid2xo FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id);


--
-- Name: menu_items fkhaqtoboitpl0n541y0sc753my; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT fkhaqtoboitpl0n541y0sc753my FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: delivery fkm2m0si8jd1k9hxkt2aqkpwqr2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fkm2m0si8jd1k9hxkt2aqkpwqr2 FOREIGN KEY (delivery_person_id) REFERENCES public.users(id);


--
-- Name: restaurants fkp5mmmypepihvmkdb83qwugr4d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT fkp5mmmypepihvmkdb83qwugr4d FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: delivery fku4e8rjwmg09vmas3ccjwglso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fku4e8rjwmg09vmas3ccjwglso FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- PostgreSQL database dump complete
--

