server:
  port : 8081
spring:
  application:
    name : "food-delivery-system"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  springdoc:
    swagger-ui:
      enabled: true
      path: "/swagger-ui.html"


